// frontend/src/App.jsx
import Header from "./components/Header";
import Scanner from "./pages/Scanner";
import Auth from "./pages/Auth";
import React from "react";
import { BrowserRouter as Router, Routes, Route, Navigate, useLocation, useNavigate } from "react-router-dom";

function RequireAuth({ children, authenticated }) {
  const location = useLocation();
  if (!authenticated) {
    return <Navigate to="/auth" state={{ from: location }} replace />;
  }
  return children;
}

export default function App() {
  const [authenticated, setAuthenticated] = React.useState(false);
  const [checking, setChecking] = React.useState(true);

  React.useEffect(() => {
    (async () => {
      try {
        const res = await fetch("/api/me", { credentials: "include" });
        setAuthenticated(res.ok);
      } catch {
        setAuthenticated(false);
      } finally {
        setChecking(false);
      }
    })();
  }, []);

  const signOut = async () => {
    try {
      await fetch("/api/logout", { method: "POST", credentials: "include" });
    } catch (e) {}
    setAuthenticated(false);
  };

  if (checking) return null;

  return (
    <Router>
      <Header authenticated={authenticated} onSignOut={signOut} />
      <main>
        <Routes>
          <Route path="/scanner" element={
            <RequireAuth authenticated={authenticated}>
              <Scanner />
            </RequireAuth>
          } />
          <Route path="/auth" element={<Auth />} />
          <Route path="*" element={<Navigate to="/scanner" replace />} />
        </Routes>
      </main>
    </Router>
  );
}

// frontend/src/App.svelte
<script>
  import Router from 'svelte-spa-router';
  import Scanner from './pages/Scanner.svelte';
  import Signup from './pages/Signup.svelte';
  import Login from './pages/Login.svelte';
  import Header from './components/Header.svelte';
  import { onMount } from 'svelte';

  const routes = {
    '/scanner': Scanner,
    '/signup': Signup,
    '/login': Login,
  };

  let authenticated = false;
  let checking = true;

  onMount(async () => {
    try {
      const res = await fetch('/api/me', { credentials: 'include' }); // endpoint returns 200 if authenticated
      authenticated = res.ok;
    } catch {
      authenticated = false;
    } finally {
      checking = false;
    }
  });

  async function signOut() {
    try {
      await fetch('/api/logout', { method: 'POST', credentials: 'include' });
    } catch (e) {
      // ignore network errors, still flip UI
    }
    authenticated = false;
  }
</script>

<Header {authenticated} onSignOut={signOut} />

<main>
  <Router {routes}/>
</main>
